"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Locale = 'ru' | 'en' | 'ky' | 'uz';

export const translations = {
  ru: {
    common: {
      dashboard: 'Дашборд',
      appointments: 'Записи',
      services: 'Услуги',
      clients: 'Клиенты',
      settings: 'Настройки бота',
      admin: 'Админ-панель',
      logout: 'Выйти',
      theme: 'Тема',
      language: 'Язык',
      upgrade: 'Улучшить',
      trial_expired: 'Истек',
      access: 'Доступ',
      days_left: 'дн. осталось',
      save: 'Сохранить',
      cancel: 'Отмена',
      currency: 'сом',
      minutes: 'мин',
      search_placeholder: 'Поиск по имени или ID...',
      loading: 'Загрузка...',
      support_247: 'Поддержка 24/7'
    },
    dashboard: {
      title: 'Главная',
      subtitle: 'Аналитика и статистика за весь период',
      active_partner: 'Авторизованный партнер',
      active_apts: 'Активные записи',
      clients_base: 'База клиентов',
      revenue: 'Выручка (сом)',
      today_apts: 'Сегодняшние',
      recent_activity: 'Последняя активность',
      view_all: 'Смотреть аналитику',
      no_activity: 'Нет недавней активности',
      verified: 'Подтверждено',
      denied: 'Отменено',
      awaiting: 'Ожидает',
      revenue_growth: 'Рост выручки',
      appointments_stats: 'Статистика записей',
      average_bill: 'Средний чек',
      insights: 'Инсайты',
      promo_title: 'AuraSync Premium',
      promo_subtitle: 'Автоматизируйте свой бизнес сегодня.',
      promo_btn: 'Активировать',
      insights_desc: 'Система зафиксировала пик активности в пятницу вечером. Рекомендуем добавить бонусную заманчивую услугу.',
      report_btn: 'Смотреть отчет',
      distribution_title: 'Распределение',
      retail_label: 'Ритейл',
      services_label: 'Услуги',
      other_label: 'Прочее',
      activity_new: 'Новая запись',
      activity_client: 'Клиент',
      activity_ago: 'назад'
    },
    services: {
      title: 'Услуги',
      subtitle: 'Управление каталогом услуг и ценами',
      add: 'Новая услуга',
      no_services: 'Услуги еще не добавлены',
      form_name: 'Название услуги',
      form_name_ph: 'например, Стрижка',
      form_price: 'Стоимость (сом)',
      duration: 'Длительность'
    },
    clients: {
      title: 'База клиентов',
      subtitle: 'История посещений и профили',
      table_visits: 'Визиты',
      table_last_visit: 'Последний визит',
      table_contact: 'Связь',
      no_visits: 'Нет визитов',
      no_clients: 'Нет клиентов, соответствующих поиску'
    },
    staff: {
      title: 'Команда',
      subtitle: 'Управление сотрудниками и их графиками',
      add: 'Добавить мастера',
      no_staff: 'Сотрудники еще не добавлены',
      table_name: 'Сотрудник',
      table_role: 'Специализация',
      table_status: 'Статус',
      form_name: 'Имя мастера',
      form_role: 'Роль (например, Старший барбер)',
      status_active: 'Активен',
      status_inactive: 'Неактивен'
    },
    appointments: {
      title: 'Записи',
      subtitle: 'Управление расписанием и клиентами',
      status_verified: 'Подтверждено',
      status_denied: 'Отменено',
      status_awaiting: 'Ожидает',
      table_datetime: 'Дата / Время',
      table_price: 'Стоимость',
      table_status: 'Статус',
      table_actions: 'Управление'
    },
    settings: {
      title: 'Синхронизация Telegram',
      subtitle: 'Управление интеграцией с ботом',
      integration: 'Интеграция',
      tg_api: 'Связь с Telegram API',
      bot_token: 'Токен от BotFather',
      connecting: 'Подключение...',
      connect_btn: 'Авторизовать бота',
      success: 'Успешно подключено',
      bot_live: 'Бот активен по ссылке:',
      error: 'Ошибка подключения',
      notifications: 'Уведомления',
      notifications_desc: 'Статусы и настройки',
      how_to_start: 'Запуск уведомлений',
      how_to_start_desc: 'Для получения системных уведомлений отправьте команду',
      system_status: 'Статус системы',
      status_ok: 'Работает стабильно',
      security: 'Безопасность',
      security_desc: 'Ключи протокола защищены алгоритмом AES-256. Мы не имеем прямого доступа к вашим API-данным.',
      tips: 'Рекомендации',
      tip_1: 'Настройте логотип компании через BotFather',
      tip_2: 'Добавьте описание бренда для повышения доверия',
      tip_3: 'Настройте главное меню бота для удобной навигации',
      invalid_token: 'Некорректный токен бота'
    },
    auth: {
      login_title: 'Вход в систему',
      login_subtitle: 'Добро пожаловать в AuraSync',
      login_btn: 'Войти в кабинет',
      register_title: 'Регистрация',
      register_subtitle: 'Создайте аккаунт для вашего бизнеса',
      register_btn: 'Начать 7 дней бесплатно',
      email: 'Email адрес',
      password: 'Пароль',
      business_name: 'Название компании',
      no_account: 'Нет аккаунта?',
      have_account: 'Уже есть аккаунт?',
      join: 'Зарегистрироваться',
      sign_in: 'Войти',
      success_title: 'Заявка отправлена',
      success_desc: 'Ссылка для входа отправлена на ваш email:',
      back_to_login: 'Вернуться ко входу',
      no_card: 'Без кредитной карты'
    },
    billing: {
      title: 'Тарифы и оплата',
      subtitle: 'Активация лицензии и управление подпиской',
      plan_name: 'AuraSync Pro',
      plan_desc: 'Полный доступ ко всем функциям',
      price: '1200',
      price_period: 'в месяц',
      enterprise_tag: 'Для бизнеса',
      features: [
        'Неограниченное количество записей',
        'Брендированный Telegram-бот',
        'Управление услугами и мастерами',
        'CRM система клиентов',
        'Уведомления в Telegram',
        'Аналитика выручки',
        'Поддержка 24/7'
      ],
      buy_btn: 'Активировать подписку',
      popular_tag: 'Популярно',
      status_title: 'Статус подписки',
      status_subtitle: 'Детали вашей лицензии',
      tier: 'Ваш тариф',
      tier_free: 'Триальный период',
      tier_pro: 'Pro Доступ',
      deadline: 'Срок действия',
      days_left_status: 'дней осталось',
      how_to_pay: 'Как оплатить?',
      pay_steps: [
        'Нажмите кнопку «Активировать»',
        'Свяжитесь с менеджером в Telegram',
        'Выберите удобный способ оплаты',
        'Подписка активируется мгновенно'
      ],
      expired_title: 'Доступ ограничен',
      expired_desc: 'Ваш пробный период закончился. Продлите подписку для продолжения работы.'
    },
    admin: {
      title: 'Панель управления',
      subtitle: 'Управление бизнесами и подписками',
      stats_total: 'Всего компаний',
      stats_active: 'Активных подписок',
      stats_revenue: 'Ожидаемый доход',
      search_ph: 'Поиск по названию или email...',
      table_business: 'Компания / Владелец',
      table_status: 'Статус',
      table_deadline: 'Срок подписки',
      table_actions: 'Действия',
      table_bot_token: 'Токен бота',
      btn_add_30: '+30 дней',
      btn_add_year: '+Год',
      access_denied: 'Доступ запрещен',
      access_denied_desc: 'У вас нет прав для просмотра этой страницы.',
      days_remaining: 'дней осталось'
    },
    modules: {
      title: 'Модули',
      subtitle: 'Расширьте возможности вашего бизнеса',
      shop: 'Магазин',
      shop_desc: 'Продажа товаров через Telegram бота',
      ai: 'AI-Консультант',
      ai_desc: 'Умные ответы на вопросы клиентов через GPT',
      support: 'Поддержка',
      support_desc: 'Система тикетов для помощи клиентам',
      status_enabled: 'Включен',
      status_disabled: 'Выключен',
      btn_configure: 'Настроить',
      ai_config_title: 'Настройка AI-Консультанта',
      ai_config_key: 'OpenAI API Key',
      ai_config_prompt: 'Системный Промпт (Инструкция)',
      ai_config_knowledge: 'База Знаний (Инфо о бизнесе)',
      ai_config_help: 'Расскажите боту подробнее о вашем бизнесе, услугах и правилах. Чем больше деталей, тем точнее будут ответы.'
    },
    crm: {
      client_notes: 'Заметки о клиенте',
      notes_placeholder: 'Добавьте детали (предпочтения, аллергии)...',
      rfm_status: 'Статус лояльности',
      rfm_active: 'Лояльный',
      rfm_at_risk: 'Под риском',
      rfm_lost: 'Потерян',
      history_none: 'История покупок пуста'
    },
    landing: {
      hero_title: 'Ваш бизнес в Telegram на автопилоте',
      hero_subtitle: 'Единая экосистема для записи, продаж и управления клиентами. Запустите своего персонального бота за 5 минут.',
      get_started: 'Попробовать бесплатно',
      view_demo: 'Посмотреть демо',
      hero_btn_secondary: 'Возможности',
      nav_features: 'Возможности',
      nav_pricing: 'Тарифы',
      nav_demo: 'Демо',
      features_title: 'Всё, что нужно для роста',
      feature_booking: 'Умная запись',
      feature_booking_desc: 'Автоматическое планирование и напоминания клиентам.',
      feature_ai: 'AI-Консультант',
      feature_ai_desc: 'Бот отвечает на вопросы и продает услуги за вас.',
      feature_analytics: 'Аналитика',
      feature_analytics_desc: 'Полный контроль над доходами и эффективностью.',
      pricing_title: 'Простые тарифы',
      pricing_subtitle: 'Выберите план, который подходит вашему масштабу',
      plan_trial: 'Пробный период',
      plan_pro: 'Pro Лицензия',
      plan_trial_price: '0',
      plan_pro_price: '1500',
      period_day: 'дней',
      period_month: 'в месяц',
      most_popular: 'Популярный',
      btn_trial: 'Начать бесплатно',
      btn_pro: 'Получить доступ',
      showcase_badge: 'Живое демо',
      showcase_title_1: 'Как это',
      showcase_title_2: 'работает',
      showcase_subtitle: 'Запустите автоматизацию менее чем за 5 минут.',
      step1_title: 'Подключите BotFather',
      step1_desc: 'Просто вставьте токен вашего Telegram-бота. Без кода и серверов.',
      step2_title: 'Настройка ИИ',
      step2_desc: 'Обучите ИИ-ассистента специфике вашего бизнеса для ответов 24/7.',
      step3_title: 'Запуск',
      step3_desc: 'Поделитесь ссылкой на бота и принимайте записи и оплату.',
      learn_more: 'Подробнее',
      cta_title_1: 'Готовы увидеть',
      cta_title_2: 'реальную мощь?',
      cta_subtitle: 'Присоединяйтесь к 200+ компаниям, которые уже автоматизировали свой бизнес.',
      try_free: 'Начать бесплатно',
      demo_cta_title: 'Попробуйте AuraSync для своего бизнеса',
      demo_cta_subtitle: 'Получите 7-дневный пробный доступ и узнайте, как автоматизация изменит вашу работу уже сегодня.',
      demo_register_btn: 'Зарегистрироваться сейчас',
      features_pro: ['Полная AI экосистема', 'Складской учет / Магазин', 'Приоритетная поддержка', 'Свой брендинг', 'Продвинутая аналитика'],
      features_trial: ['Умная запись', 'База клиентов', 'Стандартный дашборд', 'Уведомления админу'],
      hero_adv_1_title: '7-дневный триал',
      hero_adv_1_desc: 'Полный доступ ко всем функциям без ограничений.',
      hero_adv_2_title: 'Без карты',
      hero_adv_2_desc: 'Начните пользоваться без привязки банковской карты.',
      hero_adv_3_title: 'Поддержка 24/7',
      hero_adv_3_desc: 'Ваш бизнес всегда под контролем нашей команды.',
      footer_address: 'Кыргызстан, г. Бишкек, ул. Московская 123',
      footer_copyright: '© 2026 AuraSync Platform. Все права защищены.',
      privacy: 'Конфиденциальность',
      terms: 'Условия',
      support: 'Поддержка',
      demo_badge: 'Демо-режим • Только чтение',
      demo_revenue_analytics: 'Аналитика выручки',
      demo_top_services: 'Топ услуг',
      demo_generate_ai: 'AI-аудит',
      demo_queue: 'Управление записями',
      demo_today: 'Сегодня',
      demo_week: 'Неделя',
      demo_th_client: 'Клиент',
      demo_th_service: 'Услуга',
      demo_th_specialist: 'Специалист',
      demo_th_status: 'Статус',
      demo_confirmed: 'Подтверждена',
      demo_in_progress: 'В процессе',
      demo_waiting: 'Ожидание',
      demo_upcoming: 'Предстоит',
      demo_all_items: 'Все товары',
      demo_add_stock: 'Добавить товар',
      demo_qty: 'Кол-во',
      demo_active_broadcasts: 'Активные рассылки',
      demo_delivered: 'Доставлено',
      demo_broadcast_power: 'Сила рассылок',
      demo_broadcast_tip: 'Увеличьте повторные визиты на 40%, отправляя автоматические бонусы клиентам, которые не приходили 30 дней.',
      demo_setup_auto: 'Настроить автоматизацию',
      demo_th_loyalty: 'Лояльность',
      demo_th_visits: 'Визиты',
      demo_th_ltv: 'LTV (Пожизненная ценность)',
      demo_times: 'раз',
      demo_bot_engine: 'Ядро бота',
      demo_bot_status: 'Статус BotFather',
      demo_api_ok: 'API ПОДКЛЮЧЕН',
      demo_token: 'Telegram Токен',
      demo_save_readonly: 'Сохранить (Только чтение)',
      demo_alerts: 'Уведомления админа',
      demo_alert_apt: 'Новые записи',
      demo_alert_revenue: 'Ежедневный отчёт',
      demo_alert_retention: 'Удержание клиентов',
      demo_configure: 'Настроить',
      demo_manage: 'Управлять',
      demo_unlock: 'Разблокировать (Pro)',
      demo_booking_desc: 'Умная система записи через Telegram с автоматическими напоминаниями.'
    },
    shop: {
      title: 'Каталог товаров',
      subtitle: 'Управляйте ассортиментом вашего магазина',
      add_product: 'Добавить товар',
      product_name: 'Название товара',
      product_price: 'Цена',
      product_stock: 'В наличии (шт)',
      product_desc: 'Описание',
      product_img: 'Ссылка на фото',
      status_instock: 'В наличии',
      status_outofstock: 'Нет в наличии',
      no_products: 'В каталоге пока нет товаров.',
      btn_edit: 'Изменить',
      btn_delete: 'Удалить'
    },
    marketing: {
      title: 'Рассылки',
      subtitle: 'Push-уведомления для ваших клиентов',
      send_btn: 'Отправить всем',
      message_ph: 'Введите текст сообщения...',
      history: 'История кампаний',
      no_campaigns: 'Кампаний еще не было',
      success_sent: 'Сообщение успешно отправлено!',
      stats_sent: 'Доставлено',
      stats_failed: 'Ошибок',
      desc: 'Отправляйте новости, акции и спецпредложения всем клиентам вашего бота мгновенно.'
    },
    bot: {
      title: 'Конструктор бота',
      subtitle: 'Настройка сообщений и интерфейса вашего Telegram бота',
      save_btn: 'Сохранить изменения',
      saving: 'Сохранение...',
      saved: 'Изменения применены',
      deploy: 'Опубликовать настройки',
      section_logic: 'Логика и тексты',
      section_logic_desc: 'Шаблоны сообщений бота',
      welcome_label: 'Приветствие (/start)',
      welcome_ph: 'Текст, который увидит клиент при запуске бота...',
      about_label: 'О нас (описание бренда)',
      about_ph: 'Расскажите о вашей компании и ценностях...',
      contact_label: 'Контакты и адрес',
      contact_ph: 'Укажите адрес, телефон и режим работы...',
      section_visual: 'Визуальный стиль',
      section_visual_desc: 'Оформление интерфейса',
      emoji_label: 'Главный эмодзи',
      simulator_title: 'Предпросмотр (Telegram)',
      status_online: 'онлайн',
      btn_schedule: 'Записаться на услуг',
      btn_about: 'О компании',
      btn_contacts: 'Контакты',
      btn_history: 'Мои записи'
    }
  },
  en: {
    common: {
      dashboard: 'Dashboard',
      appointments: 'Appointments',
      services: 'Services',
      clients: 'Clients',
      settings: 'Bot Settings',
      admin: 'Admin Panel',
      logout: 'Log Out',
      theme: 'Theme',
      language: 'Language',
      upgrade: 'Upgrade',
      trial_expired: 'Expired',
      access: 'Access',
      days_left: 'days left',
      save: 'Save',
      cancel: 'Cancel',
      currency: 'KGS',
      minutes: 'min',
      search_placeholder: 'Search by Name or ID...',
      loading: 'Loading...',
      support_247: '24/7 Support'
    },
    dashboard: {
      title: 'Overview',
      subtitle: 'System analytics and operational monitoring',
      active_partner: 'Authorized Partner',
      active_apts: 'Active Appointments',
      clients_base: 'Client Base',
      revenue: 'Revenue (KGS)',
      today_apts: 'Today\'s Appointments',
      recent_activity: 'Recent Activity',
      view_all: 'View Analytics',
      no_activity: 'No recent activity',
      verified: 'Verified',
      denied: 'Denied',
      awaiting: 'Awaiting',
      revenue_growth: 'Revenue Growth',
      appointments_stats: 'Booking Trends',
      average_bill: 'Average Receipt',
      insights: 'AI Insights',
      promo_title: 'AuraSync Premium',
      promo_subtitle: 'Autonomous infrastructure for global scale.',
      promo_btn: 'Activate',
      insights_desc: 'System detected peak activity on Friday evening. We recommend adding a bonus service.',
      report_btn: 'View Report',
      distribution_title: 'Distribution',
      retail_label: 'Retail',
      services_label: 'Services',
      other_label: 'Other',
      activity_new: 'New Appointment',
      activity_client: 'Client',
      activity_ago: 'ago'
    },
    services: {
      title: 'Services',
      subtitle: 'Manage your service catalog and pricing',
      add: 'New Service',
      no_services: 'No services deployed yet',
      form_name: 'Service Name',
      form_name_ph: 'e.g., Haircut',
      form_price: 'Price (KGS)',
      duration: 'Duration'
    },
    clients: {
      title: 'Clients',
      subtitle: 'Client base and history',
      table_visits: 'Visits',
      table_last_visit: 'Last Visit',
      table_contact: 'Contact',
      no_visits: 'No visits',
      no_clients: 'No clients found matching search'
    },
    staff: {
      title: 'Team',
      subtitle: 'Manage staff members and schedules',
      add: 'Add Specialist',
      no_staff: 'No staff members added yet',
      table_name: 'Specialist',
      table_role: 'Role',
      table_status: 'Status',
      form_name: 'Specialist Name',
      form_role: 'Role (e.g., Master Barber)',
      status_active: 'Active',
      status_inactive: 'Inactive'
    },
    appointments: {
      title: 'Schedule',
      subtitle: 'Manage your bookings and schedule',
      status_verified: 'Verified',
      status_denied: 'Denied',
      status_awaiting: 'Pending',
      table_datetime: 'Date / Time',
      table_price: 'Price',
      table_status: 'Status',
      table_actions: 'Actions'
    },
    settings: {
      title: 'Telegram Sync',
      subtitle: 'Manage Bot Integration API',
      integration: 'Integration',
      tg_api: 'Telegram API Connection',
      bot_token: 'BotFather Secure Token',
      connecting: 'Connecting...',
      connect_btn: 'Authorize Bot',
      success: 'Connection Authorized',
      bot_live: 'Bot is active at:',
      error: 'Connection Error',
      notifications: 'Operational Alerts',
      notifications_desc: 'Alert status and triggers',
      how_to_start: 'Initialize Alerts',
      how_to_start_desc: 'Send to your business account: ',
      system_status: 'System Resilience',
      status_ok: 'Stable System',
      security: 'Encryption Layer',
      security_desc: 'Keys are secured via AES-256 standards. We operate zero-knowledge architecture over your API credentials.',
      tips: 'Optimization Logs',
      tip_1: 'Set organizational logo in BotFather',
      tip_2: 'Define brand description to increase trust metric',
      tip_3: 'Initialize bot command menu for direct routing',
      invalid_token: 'Invalid bot token'
    },
    auth: {
      login_title: 'Sign In',
      login_subtitle: 'Welcome to AuraSync portal',
      login_btn: 'Login to Cabinet',
      register_title: 'Create Account',
      register_subtitle: 'Start automating your business today',
      register_btn: 'Start 7-Day Free Trial',
      email: 'Email Address',
      password: 'Password',
      business_name: 'Business Name',
      no_account: 'No account?',
      have_account: 'Already have an account?',
      join: 'Sign Up',
      sign_in: 'Sign In',
      success_title: 'Confirmation Sent',
      success_desc: 'A login link has been sent to your email:',
      back_to_login: 'Back to Login',
      no_card: 'No Credit Card Required'
    },
    billing: {
      title: 'Plans & Billing',
      subtitle: 'Activate your license and manage subscription',
      plan_name: 'AuraSync Pro',
      plan_desc: 'Complete access to all functions',
      price: '15',
      price_period: 'per month',
      enterprise_tag: 'For Business',
      features: [
        'Unlimited appointments',
        'Branded Telegram bot',
        'Service & Staff management',
        'Client CRM system',
        'Telegram notifications',
        'Revenue analytics',
        '24/7 Support'
      ],
      buy_btn: 'Activate Subscription',
      popular_tag: 'Popular',
      status_title: 'Subscription Status',
      status_subtitle: 'Your license details',
      tier: 'Current Plan',
      tier_free: 'Trial Period',
      tier_pro: 'Pro Access',
      deadline: 'Expiration Date',
      days_left_status: 'days left',
      how_to_pay: 'How to pay?',
      pay_steps: [
        'Click "Activate" button',
        'Contact manager in Telegram',
        'Choose payment method',
        'Subscription activates instantly'
      ],
      expired_title: 'Access Restricted',
      expired_desc: 'Your trial period has ended. Please renew to continue.'
    },
    admin: {
      title: 'Admin Control',
      subtitle: 'Manage businesses and subscriptions',
      stats_total: 'Total Businesses',
      stats_active: 'Active Subscriptions',
      stats_revenue: 'Projected MRR',
      search_ph: 'Filter by name or email...',
      table_business: 'Business / Owner',
      table_status: 'Status',
      table_deadline: 'Deadline',
      table_actions: 'Actions',
      table_bot_token: 'Bot Token',
      btn_add_30: '+30 Days',
      btn_add_year: '+Annual',
      access_denied: 'Access Denied',
      access_denied_desc: 'You do not have permissions to view this page.',
      days_remaining: 'days left'
    },
    modules: {
      title: 'Modules',
      subtitle: 'Extend your business capabilities',
      shop: 'Shop',
      shop_desc: 'Sell products directly via Telegram',
      ai: 'AI Consultant',
      ai_desc: 'Smart GPT-powered customer responses',
      support: 'Support Hub',
      support_desc: 'Ticket system for customer assistance',
      status_enabled: 'Enabled',
      status_disabled: 'Disabled',
      btn_configure: 'Configure',
      ai_config_title: 'AI Consultant Settings',
      ai_config_key: 'OpenAI API Key',
      ai_config_prompt: 'System Prompt (Instructions)',
      ai_config_knowledge: 'Knowledge Base (Business Info)',
      ai_config_help: 'Tell the bot more about your business, services, and rules. The more details you provide, the more accurate the responses will be.'
    },
    crm: {
      client_notes: 'Client Notes',
      notes_placeholder: 'Add details (preferences, allergies)...',
      rfm_status: 'Loyalty Level',
      rfm_active: 'Loyal',
      rfm_at_risk: 'At Risk',
      rfm_lost: 'Lost',
      history_none: 'Purchase history empty'
    },
    landing: {
      hero_title: 'Your Business on Autopilot in Telegram',
      hero_subtitle: 'A unified ecosystem for bookings, sales, and client management. Launch your personal bot in 5 minutes.',
      get_started: 'Try for Free',
      view_demo: 'View Demo',
      hero_btn_secondary: 'Features',
      nav_features: 'Features',
      nav_pricing: 'Pricing',
      nav_demo: 'Demo',
      features_title: 'Everything for Growth',
      feature_booking: 'Smart Booking',
      feature_booking_desc: 'Automatic scheduling and client reminders.',
      feature_ai: 'AI Consultant',
      feature_ai_desc: 'Bot answers questions and sells services for you.',
      feature_analytics: 'Analytics',
      feature_analytics_desc: 'Complete control over revenue and performance.',
      pricing_title: 'Simple Pricing',
      pricing_subtitle: 'Choose a plan that fits your scale',
      plan_trial: 'Free Trial',
      plan_pro: 'Pro License',
      plan_trial_price: '0',
      plan_pro_price: '1500',
      period_day: 'days',
      period_month: 'per month',
      most_popular: 'Most Popular',
      btn_trial: 'Start Free Trial',
      btn_pro: 'Get Full Access',
      showcase_badge: 'Live Demo',
      showcase_title_1: 'How it',
      showcase_title_2: 'Works',
      showcase_subtitle: 'Start your automation journey in under 5 minutes.',
      step1_title: 'Connect BotFather',
      step1_desc: 'Simply paste your Telegram Bot Token. No coding, no servers.',
      step2_title: 'AI Configuration',
      step2_desc: 'Train your AI assistant with your business details to handle inquiries 24/7.',
      step3_title: 'Go Live',
      step3_desc: 'Share your bot link and watch as clients book and pay.',
      learn_more: 'Learn More',
      cta_title_1: 'Ready to see',
      cta_title_2: 'the real power?',
      cta_subtitle: 'Join 200+ businesses who automated their workflow this week.',
      try_free: 'Try For Free',
      demo_cta_title: 'Experience AuraSync for your own business',
      demo_cta_subtitle: 'Get a 7-day full access trial and see how automation can transform your workflow today.',
      demo_register_btn: 'Register Now',
      features_pro: ['Full AI Ecosystem', 'Inventory/Shop Modules', 'Priority Support', 'Custom Branding', 'Advanced Analytics'],
      features_trial: ['Smart Booking', 'Client Database', 'Standard Dashboards', 'Admin Notifications'],
      hero_adv_1_title: '7-Day Trial',
      hero_adv_1_desc: 'Full access to all features with no limits.',
      hero_adv_2_title: 'No Credit Card',
      hero_adv_2_desc: 'Start using without binding your bank card.',
      hero_adv_3_title: '24/7 Support',
      hero_adv_3_desc: 'Your business is always under our team\'s care.',
      footer_address: '123 Moskovskaya St, Bishkek, Kyrgyzstan',
      footer_copyright: '© 2026 AuraSync Platform. All rights reserved.',
      privacy: 'Privacy',
      terms: 'Terms',
      support: 'Support',
      demo_badge: 'Viewing Demo Mode • Read Only',
      demo_revenue_analytics: 'Revenue Analytics',
      demo_top_services: 'Top Services',
      demo_generate_ai: 'Generate AI Audit',
      demo_queue: 'Queue Management',
      demo_today: 'Today',
      demo_week: 'Week',
      demo_th_client: 'Client Info',
      demo_th_service: 'Selected Service',
      demo_th_specialist: 'Specialist',
      demo_th_status: 'Status',
      demo_confirmed: 'Confirmed',
      demo_in_progress: 'In Progress',
      demo_waiting: 'Waiting',
      demo_upcoming: 'Upcoming',
      demo_all_items: 'All Items',
      demo_add_stock: 'Add Stock',
      demo_qty: 'Qty',
      demo_active_broadcasts: 'Active Broadcasts',
      demo_delivered: 'Delivered',
      demo_broadcast_power: 'Broadcast Power',
      demo_broadcast_tip: 'Drive 40% more repeats by sending automated rewards to clients who haven\'t visited in 30 days.',
      demo_setup_auto: 'Setup Automation',
      demo_th_loyalty: 'Loyalty Status',
      demo_th_visits: 'Total Visits',
      demo_th_ltv: 'LTV (Lifetime Value)',
      demo_times: 'times',
      demo_bot_engine: 'Bot Engine Core',
      demo_bot_status: 'BotFather Status',
      demo_api_ok: 'API CONNECTED',
      demo_token: 'Telegram Token',
      demo_save_readonly: 'Save Changes (Read Only)',
      demo_alerts: 'Admin Alerts',
      demo_alert_apt: 'New Appointment Notifications',
      demo_alert_revenue: 'Daily Revenue Summary',
      demo_alert_retention: 'Client Retention Alerts',
      demo_configure: 'Configure',
      demo_manage: 'Manage Flow',
      demo_unlock: 'Upgrade to Unlock',
      demo_booking_desc: 'Smart Telegram-based booking system with automated reminders.'
    },
    shop: {
      title: 'Product Catalog',
      subtitle: 'Manage your store inventory',
      add_product: 'Add Product',
      product_name: 'Product Name',
      product_price: 'Price',
      product_stock: 'Stock Amount',
      product_desc: 'Description',
      product_img: 'Image URL',
      status_instock: 'In Stock',
      status_outofstock: 'Out of Stock',
      no_products: 'No products in catalog yet.',
      btn_edit: 'Edit',
      btn_delete: 'Delete'
    },
    marketing: {
      title: 'Broadcasts',
      subtitle: 'Push notifications for your clients',
      send_btn: 'Send to All',
      message_ph: 'Enter message text...',
      history: 'Campaign History',
      no_campaigns: 'No campaigns yet',
      success_sent: 'Message sent successfully!',
      stats_sent: 'Delivered',
      stats_failed: 'Failed',
      desc: 'Send news, promotions, and special offers to all your bot clients instantly.'
    },
    bot: {
      title: 'Bot Builder',
      subtitle: 'Customize messages and UI for your Telegram bot',
      save_btn: 'Save Changes',
      saving: 'Synchronizing...',
      saved: 'Artifact Stored',
      deploy: 'Deploy Protocol',
      section_logic: 'Logic Parameters',
      section_logic_desc: 'Bot message archetypes',
      welcome_label: 'Welcome Hook (/start)',
      welcome_ph: 'System initialization message...',
      about_label: 'Brand Story (About)',
      about_ph: 'Corporate mission and values...',
      contact_label: 'Contact Matrix',
      contact_ph: 'Operational contact endpoints...',
      section_visual: 'Visual Identity',
      section_visual_desc: 'UI Aesthetic markers',
      emoji_label: 'Protocol Emoji Accent',
      simulator_title: 'Protocol Simulator',
      status_online: 'online',
      btn_schedule: 'Schedule Session',
      btn_about: 'Brand Story',
      btn_contacts: 'Contacts',
      btn_history: 'Session History'
    }
  },
  ky: {
    common: {
      dashboard: 'Башкы бет',
      appointments: 'Жазылуулар',
      services: 'Кызматтар',
      clients: 'Кардарлар',
      settings: 'Жөндөөлөр',
      admin: 'Башкаруу',
      logout: 'Чыгуу',
      theme: 'Тема',
      language: 'Тил',
      upgrade: 'Жакшыртуу',
      trial_expired: 'Бүткөн',
      access: 'Кирүү',
      days_left: 'күн калды',
      save: 'Сактоо',
      cancel: 'Жокко чыгаруу',
      currency: 'сом',
      minutes: 'мүн',
      search_placeholder: 'Аты же ID боюнча издөө...',
      loading: 'Жүктөлүүдө...',
      support_247: '24/7 Колдоо'
    },
    dashboard: {
      title: 'Негизги',
      subtitle: 'Талдоо жана акыркы окуялар',
      active_partner: 'Ыйгарым укуктуу өнөктөш',
      active_apts: 'Активдүү жазылуулар',
      clients_base: 'Кардарлар базасы',
      revenue: 'Киреше (сом)',
      today_apts: 'Бүгүн жазылгандар',
      recent_activity: 'Акыркы аракеттер',
      view_all: 'Аналитика',
      no_activity: 'Аракеттер жок',
      verified: 'Тастыкталды',
      denied: 'Жокко чыгарылды',
      awaiting: 'Күтүүдө',
      revenue_growth: 'Кирешенин өсүшү',
      appointments_stats: 'Жазылуулар статистикасы',
      average_bill: 'Орточо чек',
      insights: 'Инсайттар',
      promo_title: 'AuraSync Premium',
      promo_subtitle: 'Бизнесиңизди бүгүн автоматташтырыңыз.',
      promo_btn: 'Активдештирүү',
      insights_desc: 'Система жума күнү кечинде активдүүлүктүн туу чокусун каттады. Бонустук кызмат кошууну сунуштайбыз.',
      report_btn: 'Отчетту көрүү',
      distribution_title: 'Бөлүштүрүү',
      retail_label: 'Ритейл',
      services_label: 'Кызматтар',
      other_label: 'Башкасы',
      activity_new: 'Жаңы жазуу',
      activity_client: 'Кардар',
      activity_ago: 'мурун'
    },
    services: {
      title: 'Кызматтар',
      subtitle: 'Кызматтарды жана бааларды башкаруу',
      add: 'Жаңы кызмат',
      no_services: 'Кызматтар кошула элек',
      form_name: 'Кызматтын аты',
      form_name_ph: 'мисалы, Чач кыркуу',
      form_price: 'Баасы (сом)',
      duration: 'Узактыгы'
    },
    clients: {
      title: 'Кардарлар',
      subtitle: 'Келүү тарыхы жана профилдер',
      table_visits: 'Келүү саны',
      table_last_visit: 'Акыркы келүү',
      table_contact: 'Байланыш',
      no_visits: 'Келүү жок',
      no_clients: 'Ылайыктуу кардарлар табылбады'
    },
    staff: {
      title: 'Команда',
      subtitle: 'Кызматкерлерди жана алардын графиктерин башкаруу',
      add: 'Мастер кошуу',
      no_staff: 'Кызматкерлер кошула элек',
      table_name: 'Кызмеркер',
      table_role: 'Адистиги',
      table_status: 'Статус',
      form_name: 'Мастердин аты',
      form_role: 'Ролу (мисалы, Башкы барбер)',
      status_active: 'Активдүү',
      status_inactive: 'Активдүү эмес'
    },
    appointments: {
      title: 'Жазылуулар',
      subtitle: 'Убакытты жана графиктерди башкаруу',
      status_verified: 'Тастыкталды',
      status_denied: 'Жокко чыгарылды',
      status_awaiting: 'Күтүүдө',
      table_datetime: 'Күнү / Убактысы',
      table_price: 'Баасы',
      table_status: 'Статус',
      table_actions: 'Башкаруу'
    },
    settings: {
      title: 'Telegram Синхрондоштуруу',
      subtitle: 'Ботту интеграциялоону башкаруу',
      integration: 'Интеграция',
      tg_api: 'Telegram API менен байланыш',
      bot_token: 'BotFather Токени',
      connecting: 'Туташууда...',
      connect_btn: 'Ботту авторизациялоо',
      success: 'Ийгиликтүү туташты',
      bot_live: 'Бот активдүү: ',
      error: 'Туташуу катасы',
      notifications: 'Билдирмелер',
      notifications_desc: 'Тартип жана статустар',
      how_to_start: 'Билдирмелерди иштетүү',
      how_to_start_desc: 'Билдирмелер үчүн буйрук жөнөтүңүз:',
      system_status: 'Системанын абалы',
      status_ok: 'Туруктуу иштөөдө',
      security: 'Коопсуздук',
      security_desc: 'Протокол ачкычтары AES-256 менен корголгон. Сиздин маалыматтарга түз кирүү жок.',
      tips: 'Кеңештер',
      tip_1: 'BotFather аркылуу логотипти орнотуңуз',
      tip_2: 'Ишенимди жогорулатуу үчүн брендди сүрөттөңүз',
      tip_3: 'Навигация үчүн ботнун менюсун тууралаңыз',
      invalid_token: 'Бот токени туура эмес'
    },
    auth: {
      login_title: 'Кирүү',
      login_subtitle: 'AuraSync системасына кош келиңиз',
      login_btn: 'Кабинетке кирүү',
      register_title: 'Каттоо',
      register_subtitle: 'Бизнесиңиз үчүн аккаунт ачыңыз',
      register_btn: '7 күн акысыз баштоо',
      email: 'Email дарек',
      password: 'Сыр сөз',
      business_name: 'Компаниянын аты',
      no_account: 'Аккаунт жокпу?',
      have_account: 'Аккаунт барбы?',
      join: 'Катталуу',
      sign_in: 'Кирүү',
      success_title: 'Билдирме жөнөтүлдү',
      success_desc: 'Кирүү үчүн шилтеме почтаңызга жөнөтүлдү:',
      back_to_login: 'Кирүүгө кайтуу',
      no_card: 'Кредиттик картасыз'
    },
    billing: {
      title: 'Тарифтер жана төлөм',
      subtitle: 'Лицензияны активдештирүү жана башкаруу',
      plan_name: 'AuraSync Pro',
      plan_desc: 'Бардык функцияларга толук мүмкүнчүлүк',
      price: '1200',
      price_period: 'айына',
      enterprise_tag: 'Бизнес үчүн',
      features: [
        'Чексиз жазылуулар',
        'Жеке Telegram бот',
        'Кызматтарды башкаруу',
        'CRM системасы',
        'Telegram билдирмелери',
        'Киреше аналитикасы',
        '24/7 Колдоо'
      ],
      buy_btn: 'Жазылууну активдештирүү',
      popular_tag: 'Популярдуу',
      status_title: 'Жазылуу статусу',
      status_subtitle: 'Лицензиянын деталдары',
      tier: 'Сиздин тариф',
      tier_free: 'Сыноо мөөнөтү',
      tier_pro: 'Pro Мүмкүнчүлүк',
      deadline: 'Мөөнөтү',
      days_left_status: 'күн калды',
      how_to_pay: 'Кантип төлөө керек?',
      pay_steps: [
        '«Активдештирүү» баскычын басыңыз',
        'Менеджер менен Telegram аркылуу байланышыңыз',
        'Төлөм ыкмасын тандаңыз',
        'Жазылуу дароо активдешет'
      ],
      expired_title: 'Мүмкүнчүлүк чектелди',
      expired_desc: 'Сыноо мөөнөтүңүз бүттү. Программаны улантуу үчүн жазылууну узартыңыз.'
    },
    admin: {
      title: 'Башкаруу панели',
      subtitle: 'Бизнестерди жана жазылууларды башкаруу',
      stats_total: 'Жалпы компаниялар',
      stats_active: 'Активдүү жазылуулар',
      stats_revenue: 'Киреше (окууда)',
      search_ph: 'Аты же email боюнча издөө...',
      table_business: 'Компания / Ээси',
      table_status: 'Статус',
      table_deadline: 'Мөөнөтү',
      table_actions: 'Аракеттер',
      table_bot_token: 'Бот токени',
      btn_add_30: '+30 күн',
      btn_add_year: '+Жыл',
      access_denied: 'Кирүүгө болбойт',
      access_denied_desc: 'Бул баракты көрүүгө сизде укук жок.',
      days_remaining: 'күн калды'
    },
    modules: {
      title: 'Модулдар',
      subtitle: 'Бизнесиңиздин мүмкүнчүлүктөрүн кеңейтиңиз',
      shop: 'Дүкөн',
      shop_desc: 'Telegram бот аркылуу товарларды сатуу',
      ai: 'AI-Консультант',
      ai_desc: 'GPT аркылуу кардарлардын суроолоруна жооптор',
      support: 'Колдоо',
      support_desc: 'Кардарларга жардам берүү үчүн тикеттер системасы',
      status_enabled: 'Күйүк',
      status_disabled: 'Өчүк',
      btn_configure: 'Ырастоо',
      ai_config_title: 'AI-Консультантты ырастоо',
      ai_config_key: 'OpenAI API ачкычы',
      ai_config_prompt: 'Системалык Промпт (Нускоо)',
      ai_config_knowledge: 'Билим базасы (Бизнес тууралуу маалымат)',
      ai_config_help: 'Ботуңузга бизнесиңиз, кызматтарыңыз жана эрежелериңиз жөнүндө көбүрөөк айтып бериңиз. Маалымат канчалык көп болсо, жооптор ошончолук так болот.'
    },
    crm: {
      client_notes: 'Кардар жөнүндө эскертмелер',
      notes_placeholder: 'Маалымат кошуңуз (каалоолор, аллергия)...',
      rfm_status: 'Лоялдуулук статусу',
      rfm_active: 'Туруктуу',
      rfm_at_risk: 'Тобокелдикте',
      rfm_lost: 'Жоголгон',
      history_none: 'Сатып алуу тарыхы бош'
    },
    landing: {
      hero_title: 'Telegram-дагы бизнесиңиз автопилотто',
      hero_subtitle: 'Жазуу, сатуу жана кардарларды башкаруу үчүн бирдиктүү экосистема. Өзүңүздүн ботуңузду 5 мүнөттө ишке киргизиңиз.',
      get_started: 'Акысыз аракет кылыңыз',
      view_demo: 'Демо көрүү',
      hero_btn_secondary: 'Мүмкүнчүлүктөр',
      nav_features: 'Мүмкүнчүлүктөр',
      nav_pricing: 'Тарифтер',
      nav_demo: 'Демо',
      features_title: 'Өсүү үчүн зарыл болгон нерселердин баары',
      feature_booking: 'Акылдуу жазуу',
      feature_booking_desc: 'Кардарлар үчүн автоматтык пландаштыруу жана эскертүүлөр.',
      feature_ai: 'AI-Консультант',
      feature_ai_desc: 'Бот суроолорго жооп берет жана сиз үчүн кызматтарды сатат.',
      feature_analytics: 'Аналитика',
      feature_analytics_desc: 'Киреше жана натыйжалуулукка толук көзөмөл.',
      pricing_title: 'Жөнөкөй тарифтер',
      pricing_subtitle: 'Масштабыңызга ылайыктуу планды тандаңыз',
      plan_trial: 'Сыноо мөөнөтү',
      plan_pro: 'Pro Лицензия',
      plan_trial_price: '0',
      plan_pro_price: '1500',
      period_day: 'күн',
      period_month: 'айына',
      most_popular: 'Популярдуу',
      btn_trial: 'Акысыз баштоо',
      btn_pro: 'Мүмкүнчүлүк алуу',
      showcase_badge: 'Живое демо',
      showcase_title_1: 'Ал кандай',
      showcase_title_2: 'иштейт',
      showcase_subtitle: 'Автоматташтырууну 5 мүнөткө жетпеген убакытта баштаңыз.',
      step1_title: 'BotFather-ди туташтыруу',
      step1_desc: 'Telegram бот токениңизди жөн гана чаптаңыз. Кодсуз жана серверлерсиз.',
      step2_title: 'Тартипке салуу',
      step2_desc: 'ИИ жардамчыңызды бизнесиңиздин өзгөчөлүктөрүнө жараша үйрөтүңүз.',
      step3_title: 'Ишке киргизүү',
      step3_desc: 'Боттун шилтемесин бөлүшүңүз жана жазууларды кабыл алыңыз.',
      learn_more: 'Толук маалымат',
      cta_title_1: 'Чыныгы кубаттуулукту',
      cta_title_2: 'көрүүгө даярсызбы?',
      cta_subtitle: 'Бизнесин автоматташтырган 200дөн ашуун компанияга кошулуңуз.',
      try_free: 'Акысыз баштоо',
      demo_cta_title: 'Бизнесиңиз үчүн AuraSync-ти байкап көрүңүз',
      demo_cta_subtitle: '7 күндүк акысыз мүмкүнчүлүктү алыңыз жана автоматташтыруу ишиңизди кандайча өзгөртөөрүн билиңиз.',
      demo_register_btn: 'Азыр катталыңыз',
      features_pro: ['Толук AI экосистемасы', 'Складдык эсеп / Дүкөн', 'Артыкчылыктуу колдоо', 'Өз брендинг', 'Өркүндөтүлгөн аналитика'],
      features_trial: ['Акылдуу жазуу', 'Кардарлар базасы', 'Стандарттык дашборд', 'Админге билдирүүлөр'],
      hero_adv_1_title: '7 күндүк триал',
      hero_adv_1_desc: 'Бардык функцияларга чектөөсүз толук мүмкүнчүлүк.',
      hero_adv_2_title: 'Картасыз',
      hero_adv_2_desc: 'Банк картасын байлабастан колдоно баштаңыз.',
      hero_adv_3_title: '24/7 Колдоо',
      hero_adv_3_desc: 'Сиздин бизнесиңиз ар дайым биздин команданын көзөмөлүндө.',
      footer_address: 'Кыргызстан, Бишкек ш., Московская көч. 123',
      footer_copyright: '© 2026 AuraSync Platform. Бардык укуктар корголгон.',
      privacy: 'Купуялык',
      terms: 'Шарттар',
      support: 'Колдоо',
      demo_badge: 'Демо режим • Окуу гана',
      demo_revenue_analytics: 'Киреше аналитикасы',
      demo_top_services: 'Мыкты кызматтар',
      demo_generate_ai: 'AI аудит',
      demo_queue: 'Жазуулардыбашкаруу',
      demo_today: 'Бүгүн',
      demo_week: 'Жума',
      demo_th_client: 'Кардар',
      demo_th_service: 'Кызмат',
      demo_th_specialist: 'Адис',
      demo_th_status: 'Статус',
      demo_confirmed: 'Ырасталды',
      demo_in_progress: 'Жүрүүдө',
      demo_waiting: 'Күтүүдө',
      demo_upcoming: 'Алдыда',
      demo_all_items: 'Бардык товарлар',
      demo_add_stock: 'Товар кошуу',
      demo_qty: 'Саны',
      demo_active_broadcasts: 'Жигердүү жөнөтүүлөр',
      demo_delivered: 'Жеткирилди',
      demo_broadcast_power: 'Жөнөтүү күчү',
      demo_broadcast_tip: '30 күн келбеген кардарларга автоматтык сыйлыктар жөнөтүп, кайра кайтууну 40% көбөйтүңүз.',
      demo_setup_auto: 'Автоматташтыруу',
      demo_th_loyalty: 'Берилгендик',
      demo_th_visits: 'Баруулар',
      demo_th_ltv: 'LTV',
      demo_times: 'жолу',
      demo_bot_engine: 'Бот өзөгү',
      demo_bot_status: 'BotFather статусу',
      demo_api_ok: 'API ТУТАШКАН',
      demo_token: 'Telegram Токен',
      demo_save_readonly: 'Сактоо (Окуу гана)',
      demo_alerts: 'Админ эскертүүлөрү',
      demo_alert_apt: 'Жаңы жазуу эскертүүсү',
      demo_alert_revenue: 'Күнүмдүк кирешеотчёту',
      demo_alert_retention: 'Кардар кармоо',
      demo_configure: 'Жөндөө',
      demo_manage: 'Башкаруу',
      demo_unlock: 'Ачуу (Pro)',
      demo_booking_desc: 'Telegram аркылуу акылдуу жазуу тутуму.'
    },
    shop: {
      title: 'Товарлар каталогу',
      subtitle: 'Дүкөнүңүздүн түрлөрүн башкарыңыз',
      add_product: 'Товар кошуу',
      product_name: 'Товардын аталышы',
      product_price: 'Баасы',
      product_stock: 'Кампада (даана)',
      product_desc: 'Сүрөттөмө',
      product_img: 'Сүрөткө шилтеме',
      status_instock: 'Бар',
      status_outofstock: 'Жок',
      no_products: 'Каталогдо азырынча товар жок.',
      btn_edit: 'Өзгөртүү',
      btn_delete: 'Өчүрүү'
    },
    marketing: {
      title: 'Рассылкалар',
      subtitle: 'Кардарларыңыз үчүн Push-билдирүүлөр',
      send_btn: 'Баарына жөнөтүү',
      message_ph: 'Билдирүү текстин киргизиңиз...',
      history: 'Кампаниялардын тарыхы',
      no_campaigns: 'Кампаниялар азырынча жок',
      success_sent: 'Билдирүү ийгиликтүү жөнөтүлдү!',
      stats_sent: 'Жөнөтүлдү',
      stats_failed: 'Каталар',
      desc: 'Жаңылыктарды, акцияларды жана атайын сунуштарды боттун бардык кардарларына заматта жөнөтүңүз.'
    },
    bot: {
      title: 'Бот конструктору',
      subtitle: 'Telegram ботуңуздун билдирүүлөрүн жана интерфейсин карап чыгыңыз',
      save_btn: 'Сактоо',
      saving: 'Сакталууда...',
      saved: 'Өзгөртүүлөр сакталды',
      deploy: 'Жөндөөлөрдү жарыялоо',
      section_logic: 'Логика жана тексттер',
      section_logic_desc: 'Боттун билдирүү калыптары',
      welcome_label: 'Учурашуу (/start)',
      welcome_ph: 'Бот ишке киргенде кардар көрө турган текст...',
      about_label: 'Биз жөнүндө (бренд сүрөттөмөсү)',
      about_ph: 'Компанияңыз жана баалуулуктарыңыз жөнүндө айтып бериңиз...',
      contact_label: 'Байланыш жана дарек',
      contact_ph: 'Дарек, телефон жана иштөө тартибин көрсөтүңүз...',
      section_visual: 'Визуалдык стиль',
      section_visual_desc: 'Интерфейсти жасалгалоо',
      emoji_label: 'Негизги эмодзи',
      simulator_title: 'Алдын ала көрүү (Telegram)',
      status_online: 'онлайнда',
      btn_schedule: 'Жазылуу',
      btn_about: 'Компания жөнүндө',
      btn_contacts: 'Байланыштар',
      btn_history: 'Менин жазылууларым'
    }
  },
  uz: {
    common: {
      dashboard: 'Bosh sahifa',
      appointments: 'Yozuvlar',
      services: 'Xizmatlar',
      clients: 'Mijozlar',
      settings: 'Sozlamalar',
      admin: 'Boshqaruv paneli',
      logout: 'Chiqish',
      theme: 'Mavzu',
      language: 'Til',
      upgrade: 'Yaxshilash',
      trial_expired: 'Muddati tugagan',
      access: 'Kirish',
      days_left: 'kun qoldi',
      save: 'Saqlash',
      cancel: 'Bekor qilish',
      currency: 'so\'m',
      minutes: 'daq',
      search_placeholder: 'Ism yoki ID bo\'yicha qidiruv...',
      loading: 'Yuklanmoqda...',
      support_247: '24/7 Yordam'
    },
    dashboard: {
      title: 'Asosiy',
      subtitle: 'Hisobot va faollik',
      active_partner: 'Vakolatli hamkor',
      active_apts: 'Faol yozuvlar',
      clients_base: 'Mijozlar bazasi',
      revenue: 'Daromad (som)',
      today_apts: 'Bugungi yozuvlar',
      recent_activity: 'So\'nggi faollik',
      view_all: 'Barchasini ko\'rish',
      no_activity: 'Faollik yo\'q',
      verified: 'Tasdiqlangan',
      denied: 'Bekor qilingan',
      awaiting: 'Kutilmoqda',
      revenue_growth: 'Daromad o\'sishi',
      appointments_stats: 'Yozuvlar statistikasi',
      average_bill: 'O\'rtacha chek',
      insights: 'Insaytlari',
      promo_title: 'AuraSync Premium',
      promo_subtitle: 'Bugun biznesingizni avtomatlashtiring.',
      promo_btn: 'Faollashtirish',
      insights_desc: 'Tizim juma oqshomida faollik cho\'qqisini aniqladi. Bonus xizmatini qo\'shishni tavsiya qilamiz.',
      report_btn: 'Hisobotni ko\'rish',
      distribution_title: 'Taqsimot',
      retail_label: 'Chakana savdo',
      services_label: 'Xizmatlar',
      other_label: 'Boshqa',
      activity_new: 'Yangi yozuv',
      activity_client: 'Mijoz',
      activity_ago: 'oldingi'
    },
    services: {
      title: 'Xizmatlar',
      subtitle: 'Xizmatlar va narxlarni boshqarish',
      add: 'Yangi xizmat',
      no_services: 'Hali xizmatlar qo\'shilmagan',
      form_name: 'Xizmat nomi',
      form_name_ph: 'masalan, Soch kesish',
      form_price: 'Narxi (so\'m)',
      duration: 'Davomiyligi'
    },
    clients: {
      title: 'Mijozlar',
      subtitle: 'Tashriflar tarixi va profillar',
      table_visits: 'Tashriflar',
      table_last_visit: 'Oxirgi tashrif',
      table_contact: 'Aloqa',
      no_visits: 'Tashriflar yo\'q',
      no_clients: 'Qidiruvga mos mijozlar topilmadi'
    },
    staff: {
      title: 'Jamoa',
      subtitle: 'Xodimlarni va ularning ish grafiklarini boshqarish',
      add: 'Usta qo\'shish',
      no_staff: 'Xodimlar hali qo\'shilmagan',
      table_name: 'Xodim',
      table_role: 'Mutaxassisligi',
      table_status: 'Holat',
      form_name: 'Usta ismi',
      form_role: 'Roli (masalan, Usta barber)',
      status_active: 'Faol',
      status_inactive: 'Faol emas'
    },
    appointments: {
      title: 'Yozuvlar',
      subtitle: 'Jadval va mijozlarni boshqarish',
      status_verified: 'Tasdiqlangan',
      status_denied: 'Bekor qilingan',
      status_awaiting: 'Kutilmoqda',
      table_datetime: 'Sana / Vaqt',
      table_price: 'Narxi',
      table_status: 'Holat',
      table_actions: 'Boshqaruv'
    },
    settings: {
      title: 'Telegram bilan bog\'lanish',
      subtitle: 'Bot integratsiyasini boshqarish',
      integration: 'Integratsiya',
      tg_api: 'Telegram API aloqasi',
      bot_token: 'BotFather Tokeni',
      connecting: 'Ulanmoqda...',
      connect_btn: 'Botni tasdiqlash',
      success: 'Muvaffaqiyatli ulandi',
      bot_live: 'Bot faol havolasi:',
      error: 'Ulanishda xato',
      notifications: 'Bildirishnomalar',
      notifications_desc: 'Holatlar va sozlamalar',
      how_to_start: 'Bildirishnomalarni yoqish',
      how_to_start_desc: 'Tizim xabarlari uchun buyruq yuboring:',
      system_status: 'Tizim holati',
      status_ok: 'Barqaror ishlamoqda',
      security: 'Xavfsizlik',
      security_desc: 'Protokol kalitlari AES-256 orqali himoyalangan. API ma\'lumotlariga to\'g\'ridan to\'g\'ri kirish yo\'q.',
      tips: 'Tavsiyalar',
      tip_1: 'BotFather orqali logotipni sozlang',
      tip_2: 'Ishonchni oshirish uchun brendingizni ta\'riflang',
      tip_3: 'Oson navigatsiya uchun bot menyusini sozlang',
      invalid_token: 'Bot tokeni noto\'g\'ri'
    },
    auth: {
      login_title: 'Kirish',
      login_subtitle: 'AuraSync portaliga xush kelibsiz',
      login_btn: 'Kabinetga kirish',
      register_title: 'Ro\'yxatdan o\'tish',
      register_subtitle: 'Biznesingiz uchun hisob yarating',
      register_btn: '7 kun bepul boshlash',
      email: 'Email manzili',
      password: 'Parol',
      business_name: 'Kompaniya nomi',
      no_account: 'Hisobingiz yo\'qmi?',
      have_account: 'Hisobingiz bormi?',
      join: 'Ro\'yxatdan o\'tish',
      sign_in: 'Kirish',
      success_title: 'Tasdiqlash yuborildi',
      success_desc: 'Kirish havolasi elektron pochtangizga yuborildi:',
      back_to_login: 'Kirishga qaytish',
      no_card: 'Kredit kartasiz'
    },
    billing: {
      title: 'Tariflar va to\'lov',
      subtitle: 'Litsenziyani faollashtirish va boshqarish',
      plan_name: 'AuraSync Pro',
      plan_desc: 'Barcha funktsiyalarga to\'liq kirish',
      price: '150 000',
      price_period: 'oyiga',
      enterprise_tag: 'Biznes uchun',
      features: [
        'Cheksiz yozuvlar',
        'Shaxsiy Telegram bot',
        'Xizmatlarni boshqarish',
        'CRM tizimi',
        'Telegram bildirishnomalari',
        'Daromad tahlili',
        '24/7 Qo\'llab-quvvatlash'
      ],
      buy_btn: 'Obunani faollashtirish',
      popular_tag: 'Ommabop',
      status_title: 'Obuna holati',
      status_subtitle: 'Litsenziya tafsilotlari',
      tier: 'Sizning tarifingiz',
      tier_free: 'Sinov muddati',
      tier_pro: 'Pro Kirish',
      deadline: 'Amal qilish muddati',
      days_left_status: 'kun qoldi',
      how_to_pay: 'Qanday to\'lash kerak?',
      pay_steps: [
        '«Faollashtirish» tugmasini bosing',
        'Telegram orqali menejer bilan bog\'laning',
        'To\'lov usulini tanlang',
        'Obuna darhol faollashadi'
      ],
      expired_title: 'Kirish cheklangan',
      expired_desc: 'Sinov muddatingiz tugadi. Davom etish uchun obunani yangilang.'
    },
    admin: {
      title: 'Boshqaruv paneli',
      subtitle: 'Bizneslar va obunalarni boshqarish',
      stats_total: 'Jami kompaniyalar',
      stats_active: 'Faol obunalar',
      stats_revenue: 'Kutilayotgan daromad',
      search_ph: 'Nom yoki email bo\'yicha qidiruv...',
      table_business: 'Kompaniya / Egasi',
      table_status: 'Holat',
      table_deadline: 'Muddati',
      table_actions: 'Harakatlar',
      table_bot_token: 'Bot tokeni',
      btn_add_30: '+30 kun',
      btn_add_year: '+Yil',
      access_denied: 'Kirish taqiqlangan',
      access_denied_desc: 'Sizda ushbu sahifani ko\'rish huquqi yo\'q.',
      days_remaining: 'kun qoldi'
    },
    modules: {
      title: 'Modullar',
      subtitle: 'Biznesingiz imkoniyatlarini kengaytiring',
      shop: 'Do\'kon',
      shop_desc: 'Telegram bot orqali mahsulot sotish',
      ai: 'AI Konsultant',
      ai_desc: 'GPT yordamida mijozlar savollariga javoblar',
      support: 'Qo\'llab-quvvatlash',
      support_desc: 'Mijozlarga yordam berish uchun chiptalar tizimi',
      status_enabled: 'Yoqilgan',
      status_disabled: 'O\'chirilgan',
      btn_configure: 'Sozlash',
      ai_config_title: 'AI-Konsultantni sozlash',
      ai_config_key: 'OpenAI API kaliti',
      ai_config_prompt: 'Tizim prompti (Yo\'riqnoma)',
      ai_config_knowledge: 'Bilimlar bazasi (Biznes haqida ma\'lumot)',
      ai_config_help: 'Botga biznesingiz, xizmatlaringiz va qoidalaringiz haqida batafsil ma\'lumot bering. Tafsilotlar qancha ko\'p bo\'lsa, javoblar shunchalik aniq bo\'ladi.'
    },
    crm: {
      client_notes: 'Mijoz haqida qaydlar',
      notes_placeholder: 'Tafsilotlarni qo\'shing (afzalliklar, allergiyalar)...',
      rfm_status: 'Sodiqlik holati',
      rfm_active: 'Sodiq',
      rfm_at_risk: 'Xavf ostida',
      rfm_lost: 'Yo\'qotilgan',
      history_none: 'Sotib olish tarixi bo\'sh'
    },
    landing: {
      hero_title: 'Telegramdagi biznesingiz avtopilotda',
      hero_subtitle: 'Yozilish, sotish va mijozlarni boshqarish uchun yagona ekotizim. Shaxsiy botingizni 5 daqiqada ishga tushiring.',
      get_started: 'Bepul sinab ko\'ring',
      view_demo: 'Demoni ko\'rish',
      hero_btn_secondary: 'Imkoniyatlar',
      nav_features: 'Imkoniyatlar',
      nav_pricing: 'Tariflar',
      nav_demo: 'Demo',
      features_title: 'O\'sish uchun hamma narsa',
      feature_booking: 'Aqlli yozilish',
      feature_booking_desc: 'Avtomatik rejalashtirish va mijozlarga eslatmalar.',
      feature_ai: 'AI Konsultant',
      feature_ai_desc: 'Bot savollarga javob beradi va kiziqishlarni sotadi.',
      feature_analytics: 'Analitika',
      feature_analytics_desc: 'Daromad va samaradorlikni to\'liq nazorat qilish.',
      pricing_title: 'Oddiy tariflar',
      pricing_subtitle: 'Masshtabingizga mos rejani tanlang',
      plan_trial: 'Sinov muddati',
      plan_pro: 'Pro Litsenziya',
      plan_trial_price: '0',
      plan_pro_price: '1500',
      period_day: 'kun',
      period_month: 'oyiga',
      most_popular: 'Ommabop',
      btn_trial: 'Bepul boshlash',
      btn_pro: 'Kirish huquqini olish',
      showcase_badge: 'Jonli demo',
      showcase_title_1: 'U qanday',
      showcase_title_2: 'ishlaydi',
      showcase_subtitle: 'Avtomatlashtirishni 5 daqiqadan kamroq vaqt ichida boshlang.',
      step1_title: 'BotFather-ni ulash',
      step1_desc: 'Telegram bot tokeningizni shunchaki joylashtiring. Kodsiz va serverlarsiz.',
      step2_title: 'AI sozlash',
      step2_desc: 'Sun\'iy intellekt yordamchisini biznesingizga mos ravishda o\'qiting.',
      step3_title: 'Ishga tushirish',
      step3_desc: 'Bot havolasini ulashing va buyurtmalarni qabul qiling.',
      learn_more: 'Batafsil',
      cta_title_1: 'Haqiqiy quvvatni',
      cta_title_2: 'ko\'rishga tayyormisiz?',
      cta_subtitle: 'O\'z biznesini avtomatlashtirgan 200 dan ortiq kompaniyalarga qo\'shiling.',
      try_free: 'Bepul boshlash',
      demo_cta_title: 'O\'z biznesingiz uchun AuraSync-ni sinab ko\'ring',
      demo_cta_subtitle: '7 kunlik bepul kirish huquqini oling va avtomatlashtirish ish faoliyatingizni qanday o\'zgartirishini bilib oling.',
      demo_register_btn: 'Hozir ro\'yxatdan o\'ting',
      features_pro: ['To\'liq AI ekotizimi', 'Ombor hisobi / Do\'kon', 'Ustuvor yordam', 'O\'z brendingi', 'Kengaytirilgan analitika'],
      features_trial: ['Aqlli yozilish', 'Mijozlar bazasi', 'Standart dashboard', 'Admin xabarnomalari'],
      hero_adv_1_title: '7 kunlik trial',
      hero_adv_1_desc: 'Barcha funktsiyalarga hech qanday cheklovlarsiz to\'liq kirish.',
      hero_adv_2_title: 'Kartasiz',
      hero_adv_2_desc: 'Bank kartasini bog\'lamasdan foydalanishni boshlang.',
      hero_adv_3_title: '24/7 Yordam',
      hero_adv_3_desc: 'Sizning biznesingiz har doim bizning jamoamiz nazoratida.',
      footer_address: 'G. Bishkek, Moskovskaya ko\'chasi 123, Qirg\'iziston',
      footer_copyright: '© 2026 AuraSync Platform. Barcha huquqlar himoyalangan.',
      privacy: 'Maxfiylik',
      terms: 'Shartlar',
      support: 'Yordam',
      demo_badge: 'Demo rejim • Faqat ko\'rish',
      demo_revenue_analytics: 'Daromad tahlili',
      demo_top_services: 'Top xizmatlar',
      demo_generate_ai: 'AI audit',
      demo_queue: 'Yozuvlarni boshqarish',
      demo_today: 'Bugun',
      demo_week: 'Hafta',
      demo_th_client: 'Mijoz',
      demo_th_service: 'Xizmat',
      demo_th_specialist: 'Mutaxassis',
      demo_th_status: 'Holat',
      demo_confirmed: 'Tasdiqlangan',
      demo_in_progress: 'Jarayonda',
      demo_waiting: 'Kutmoqda',
      demo_upcoming: 'Kelgusi',
      demo_all_items: 'Barcha mahsulotlar',
      demo_add_stock: 'Mahsulot qo\'shish',
      demo_qty: 'Miqdor',
      demo_active_broadcasts: 'Faol tarqatishlar',
      demo_delivered: 'Yetkazildi',
      demo_broadcast_power: 'Tarqatish kuchi',
      demo_broadcast_tip: '30 kun kelmagan mijozlarga avtomatik mukofotlar yuborib, qaytishni 40% oshiring.',
      demo_setup_auto: 'Avtomatlashtirish',
      demo_th_loyalty: 'Sadoqat',
      demo_th_visits: 'Tashriflar',
      demo_th_ltv: 'LTV',
      demo_times: 'marta',
      demo_bot_engine: 'Bot yadrosi',
      demo_bot_status: 'BotFather holati',
      demo_api_ok: 'API ULANGAN',
      demo_token: 'Telegram Token',
      demo_save_readonly: 'Saqlash (Faqat ko\'rish)',
      demo_alerts: 'Admin bildirishnomalari',
      demo_alert_apt: 'Yangi yozuv xabarnomasi',
      demo_alert_revenue: 'Kunlik daromad hisoboti',
      demo_alert_retention: 'Mijoz ushlab qolish',
      demo_configure: 'Sozlash',
      demo_manage: 'Boshqarish',
      demo_unlock: 'Ochish (Pro)',
      demo_booking_desc: 'Telegram orqali aqlli yozilish tizimi.'
    },
    shop: {
      title: 'Mahsulotlar katalogi',
      subtitle: 'Do\'koningiz assortimentini boshqaring',
      add_product: 'Mahsulot qo\'shish',
      product_name: 'Mahsulot nomi',
      product_price: 'Narxi',
      product_stock: 'Omborda (dona)',
      product_desc: 'Tavsif',
      product_img: 'Rasm havolasi',
      status_instock: 'Mavjud',
      status_outofstock: 'Mavjud emas',
      no_products: 'Katalogda hali mahsulotlar yo\'q.',
      btn_edit: 'O\'zgartirish',
      btn_delete: 'O\'chirish'
    },
    marketing: {
      title: 'Xabarlashlar',
      subtitle: 'Mijozlaringiz uchun Push-bildirishnomalar',
      send_btn: 'Barchaga yuborish',
      message_ph: 'Xabar matnini kiriting...',
      history: 'Kampaniyalar tarixi',
      no_campaigns: 'Kampaniyalar hali bo\'lmagan',
      success_sent: 'Xabar muvaffaqiyatli yuborildi!',
      stats_sent: 'Yetkazildi',
      stats_failed: 'Xatolar',
      desc: 'Yangiliklar, aksiyalar va maxsus takliflarni barcha mijozlaringizga bir zumda yuboring.'
    },
    bot: {
      title: 'Bot konstruktori',
      subtitle: 'Telegram botingizning xabarlari va interfeysini sozlang',
      save_btn: 'Saqlash',
      saving: 'Saqlanmoqda...',
      saved: 'O\'zgarishlar saqlandi',
      deploy: 'Sozlamalarni e\'lon qilish',
      section_logic: 'Mantiq va matnlar',
      section_logic_desc: 'Bot xabarlari shablonlari',
      welcome_label: 'Salomlashish (/start)',
      welcome_ph: 'Bot ishga tushganda mijoz ko\'radigan matn...',
      about_label: 'Biz haqimizda (brend tavsifi)',
      about_ph: 'Kompaniyangiz va qadriyatlaringiz haqida gapirib bering...',
      contact_label: 'Kontaktlar va manzil',
      contact_ph: 'Manzil, telefon va ish tartibini ko\'rsating...',
      section_visual: 'Vizual uslub',
      section_visual_desc: 'Interfeysni bezash',
      emoji_label: 'Asosiy emodzi',
      simulator_title: 'Ko\'rib chiqish (Telegram)',
      status_online: 'onlayn',
      btn_schedule: 'Yozilish',
      btn_about: 'Kompaniya haqida',
      btn_contacts: 'Kontaktlar',
      btn_history: 'Mening yozuvlarim'
    }
  }
};

type LanguageContextType = {
  locale: Locale;
  setLocale: (lang: Locale) => void;
  t: typeof translations.ru;
};

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [locale, setLocaleState] = useState<Locale>('ru');

  useEffect(() => {
    const saved = localStorage.getItem('app_locale') as Locale;
    if (saved && ['ru', 'en', 'ky', 'uz'].includes(saved)) {
      setLocaleState(saved);
    }
  }, []);

  const setLocale = (lang: Locale) => {
    setLocaleState(lang);
    localStorage.setItem('app_locale', lang);
  };

  const t = translations[locale] || translations.ru;

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
